## Standard kampka originated archlinux distro
FROM eugeneai/ssh-server
MAINTAINER Evgeny Cherkashin <eugeneai@irnok.net>
ENV HOME /root
RUN pacman -Sy base-devel --noconfirm --needed
RUN /root/root-cache-clean.sh

